cms/urls.py
from django.urls import path, re_path
from cms import views

app_name = "cms"

urlpatterns = [
    # This pattern matches the home page (e.g., yoursite.com/)
    path('', views.home, name='home'),
    
    # This pattern matches any other URL and passes the path as 'permalink'
    # The 're_path' is used for regular expression matching.
    re_path(r'^(?P<permalink>.+)/$', views.home, name='permalink'),
]

statistics_app/urls.py
from django.urls import path, re_path,include
from statistics_app import views

app_name = "statistics_app"

urlpatterns = [
    path('public', views.workshop_public_stats, name="public"),
    path('team', views.team_stats, name="team"),
    path('team/<int:team_id>', views.team_stats, name="team"),
]

workshop_portal/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from workshop_portal import views
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^workshop/', include('workshop_app.urls')),
    url(r'^reset/', include('django.contrib.auth.urls')),
    url(r'^page/', include('cms.urls')),
    url(r'^statistics/', include('statistics_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

statistics_app/models.py
from django.db import models

# Create your models here.

statistics_app/forms.py
# Django imports
from django import forms

# Local Imports
from workshop_app.models import states, WorkshopType


class FilterForm(forms.Form):
    from_date = forms.DateField(
        widget=forms.DateInput(
            attrs={'type': 'date', 'class': 'form-control'}
        )
    )
    to_date = forms.DateField(
        widget=forms.DateInput(
            attrs={'type': 'date', 'class': 'form-control'}
        )
    )
    workshop_type = forms.ModelChoiceField(
        queryset=WorkshopType.objects.all(), required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    state = forms.ChoiceField(
        choices=states, required=False,
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    show_workshops = forms.BooleanField(
        help_text="Show my workshops only", required=False,
    )
    sort = forms.ChoiceField(
        choices=(("date", "Oldest"), ("-date", "Latest")),
        help_text="Sort by",
        widget=forms.Select(attrs={'class': 'form-control'})
    )
    def __init__(self, *args, **kwargs):
        start = kwargs.pop("start") if "start" in kwargs else None
        end = kwargs.pop("end") if "end" in kwargs else None
        selected_state = kwargs.pop("state") if "state" in kwargs else None
        selected_type = kwargs.pop("type") if "type" in kwargs else None
        show_workshops = (kwargs.pop("show_workshops")
                            if "show_workshops" in kwargs else None)
        sort = kwargs.pop("sort") if "sort" in kwargs else None
        super(FilterForm, self).__init__(*args, **kwargs)
        self.fields["from_date"].initial = start
        self.fields["to_date"].initial = end
        self.fields["state"].initial = selected_state
        self.fields["workshop_type"].initial = selected_type
        self.fields["show_workshops"].initial = show_workshops
        self.fields["sort"].initial = sort

statistics_app/views.py
# Python Imports
import datetime as dt
import pandas as pd

# Django Imports
from django.template.loader import get_template
from django.template import RequestContext
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.http import HttpResponse

# Local Imports
from workshop_app.models import (
    Profile, User, has_profile, Workshop, WorkshopType, Testimonial,
    states
)
from teams.models import Team
from .forms import FilterForm


def is_instructor(user):
    '''Check if the user is having instructor rights'''
    return user.groups.filter(name='__instructor__').exists()


def is_email_checked(user):
    if hasattr(user, 'profile'):
        return user.profile.is_email_verified
    else:
        return False


def workshop_public_stats(request):
    user = request.user
    form = FilterForm()
    from_date = request.GET.get('from_date')
    to_date = request.GET.get('to_date')
    state = request.GET.get('state')
    workshoptype = request.GET.get('workshop_type')
    show_workshops = request.GET.get('show_workshops')
    sort = request.GET.get('sort')
    download = request.GET.get('download')

    if from_date and to_date:
        form = FilterForm(
            start=from_date, end=to_date, state=state, type=workshoptype,
            show_workshops=show_workshops, sort=sort
        )
        workshops = Workshop.objects.filter(
            date__range=(from_date, to_date), status=1
        ).order_by(sort)
        if state:
            workshops = workshops.filter(coordinator__profile__state=state)
        if workshoptype:
            workshops = workshops.filter(workshop_type_id=workshoptype)
    else:
        today = timezone.now()
        upto = today + dt.timedelta(days=15)
        workshops = Workshop.objects.filter(
            date__range=(today, upto), status=1
            ).order_by("date")
    if show_workshops:
        if is_instructor(user):
            workshops = workshops.filter(instructor_id=user.id)
        else:
            workshops = workshops.filter(coordinator_id=user.id)
    if download:
        data = workshops.values(
            "workshop_type__name", "coordinator__first_name",
            "coordinator__last_name", "instructor__first_name",
            "instructor__last_name", "coordinator__profile__state",
            "date", "status"
        )
        df = pd.DataFrame(list(data))
        if not df.empty:
            df.status.replace(
                [0, 1, 2], ['Pending', 'Success', 'Reject'], inplace=True
            )
            codes, states_map = list(zip(*states))
            df.coordinator__profile__state.replace(
                codes, states_map, inplace=True
            )
            response = HttpResponse(content_type='text/csv')
            response['Content-Disposition'] = f'attachment; filename=statistics.csv'
            output_file = df.to_csv(response, index=False)
            return response
        else:
            messages.add_message(request, messages.WARNING, "No data found")
    ws_states, ws_count = Workshop.objects.get_workshops_by_state(workshops)
    ws_type, ws_type_count = Workshop.objects.get_workshops_by_type(workshops)
    paginator = Paginator(workshops, 30)
    page = request.GET.get('page')
    workshops = paginator.get_page(page)
    context = {"form": form, "objects": workshops, "ws_states": ws_states,
               "ws_count": ws_count, "ws_type": ws_type,
               "ws_type_count": ws_type_count}
    return render(
        request, 'statistics_app/workshop_public_stats.html', context
    )


@login_required
def team_stats(request, team_id=None):
    user = request.user
    teams = Team.objects.all()
    
    # Check if there are any teams
    if not teams.exists():
        messages.add_message(
            request, messages.INFO, "No teams have been created yet. Please contact the administrator."
        )
        return redirect(reverse("workshop_app:index"))
    
    if team_id:
        try:
            team = teams.get(id=team_id)
        except Team.DoesNotExist:
            messages.add_message(
                request, messages.ERROR, "Team not found"
            )
            return redirect(reverse("statistics_app:team"))
    else:
        team = teams.first()
    
    # Check if user is a member of the team
    if not team.members.filter(user_id=user.id).exists():
        messages.add_message(
            request, messages.INFO, "You are not added to the team"
        )
        return redirect(reverse("workshop_app:index"))

    member_workshop_data = {}
    for member in team.members.all():
        workshop_count = Workshop.objects.filter(
            instructor_id=member.user.id).count()
        member_workshop_data[member.user.get_full_name()] = workshop_count
    team_labels = list(member_workshop_data.keys())
    ws_count = list(member_workshop_data.values())
    return render(
        request, 'statistics_app/team_stats.html',
        {'team_labels': team_labels, "ws_count": ws_count, 'all_teams': teams,
         'team_id': team.id}
    )

statistics_app/templates/statistics_app/paginator.html
<ul class="pagination pagination">
    {% if objects.has_previous %}
    <li class="page-item">
        <a class="page-link" href="?page=1{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}{% if request.GET.state %}&state={{ request.GET.state }}{% endif %}{% if request.GET.workshop_type %}&workshop_type={{ request.GET.workshop_type }}{% endif %}{% if request.GET.show_workshops %}&show_workshops={{ request.GET.show_workshops }}{% endif %}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}
        " aria-label="Previous">
            <span aria-hidden="true">
                <i class="fa fa-angle-double-left"></i>
            </span>
            <span class="sr-only">begin</span>
        </a>
    </li>
    {% endif %}

    {% for n in objects.paginator.page_range %}
        {% if objects.number == n %}
            <li class="page-item active">
                <span class="page-link">{{ n }}<span class="sr-only">(current)</span></span>
            </li>
        {% elif n > objects.number|add:'-5' and n < objects.number|add:'5' %}
            <li class="page-item"><a class="page-link" href="?page={{ n }}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}{% if request.GET.state %}&state={{ request.GET.state }}{% endif %}{% if request.GET.workshop_type %}&workshop_type={{ request.GET.workshop_type }}{% endif %}{% if request.GET.show_workshops %}&show_workshops={{ request.GET.show_workshops }}{% endif %}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}">{{ n }}</a></li>
        {% endif %}
    {% endfor %}

    {% if objects.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ objects.paginator.num_pages }}{% if request.GET.from_date %}&from_date={{ request.GET.from_date }}{% endif %}{% if request.GET.to_date %}&to_date={{ request.GET.to_date }}{% endif %}{% if request.GET.state %}&state={{ request.GET.state }}{% endif %}{% if request.GET.workshop_type %}&workshop_type={{ request.GET.workshop_type }}{% endif %}{% if request.GET.show_workshops %}&show_workshops={{ request.GET.show_workshops }}{% endif %}{% if request.GET.sort %}&sort={{ request.GET.sort }}{% endif %}" aria-label="Next">
                <span aria-hidden="true">
                    <i class="fa fa-angle-double-right"></i>
                </span>
                <span class="sr-only">end</span>
            </a>
        </li>
    {% endif %}
</ul>

statistics_app/templates/statistics_app/profile_stats.html
{% extends 'workshop_app/base.html' %}

{% block title %}
  Profile Statistics
{% endblock %}

{% block extra %}
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="{{URL_ROOT}}/static/workshop_app/js/bootstrap-3.3.7.min.js"></script>
  	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>

	<script type="text/javascript">
		$(function() {
			    $( "fieldset" ).controlgroup();
		});

		$(document).ready(function() {
		$('input[type=radio]').change(function() {
			        if (this.value == "CP") {
			        	var ielem = document.getElementById('instructor_data');
			        	var celem = document.getElementById('coordinator_data');
			        	ielem.style.display = "none";
			        	celem.style.display = "table";
			            }
			        else{
			        	var ielem = document.getElementById('instructor_data');
			        	var celem = document.getElementById('coordinator_data');
			        	ielem.style.display = "table";
			        	celem.style.display = "none";
			        }
		});
	});
	</script>
{% endblock %}


{% block content %}
	<div class="container">
	 	<div class="row">
			<div class="col-md-6" align="left" >
				  <fieldset data-mini="true">
				    <label for="radio-1">Instructor Statistics </label>
				    <input type="radio" name="radio-1" id="radio-1" value="IP">
				    <label for="radio-2">Coordinator Statistics</label>
				    <input type="radio" name="radio-1" id="radio-2" value="CP">
				  </fieldset>
			</div>
			<br>
			<br>
			<!-- Instructor Data Table -->
				<table class="table" id="instructor_data" style="display: none">
					<thead>
						<tr>
							<th></th>
							<th>username</th>
							<th>Full Name</th>
							<th>Institute Name</th>
							<th>Phone Number</th>
							<th>Workshop Count</th>
						</tr>
					</thead>
					{% csrf_token %}
					{% for profile_data in instructor_data %}
						<tbody>
							<tr>
								<td>{{ forloop.counter}}</td>
								<td>{{ profile_data.profile.user}}</td>
								<td>{{ profile_data.profile.user.first_name}} {{ profile_data.profile.user.last_name}}</td>
								<td>{{ profile_data.profile.institute}}</td>
								<td>{{ profile_data.profile.phone_number}}</td>
								<td>{{ profile_data.count}}</td>
							</tr>
						</tbody>
					{% endfor %}
				</table>

			<!-- Coordinator Data Table -->
				<table class="table" id="coordinator_data" style="display: none">
					<thead>
						<tr>
							<th></th>
							<th>Name</th>
							<th>Institute Name</th>
							<th>Phone Number</th>
							<th>Registration Date</th>
							<th>Workshop Count</th>
						</tr>
					</thead>
					{% csrf_token %}
					{% for profile_data in coordinator_data %}
						<tbody>
					{% if profile_data.count > 0 %}
							<tr>
								<td>{{ forloop.counter }}</td>
								<td><a href="{{ URL_ROOT }}/view_comment_profile/{{ profile_data.profile.user.id }}">
								{{ profile_data.profile.user.get_full_name }}</a></td>
								<td>{{ profile_data.profile.institute}}</td>
								<td>{{ profile_data.profile.phone_number}}</td>
								<td>{{ profile_data.profile.user.date_joined | date}}</td>
								<td>{{ profile_data.count}}</td>
							</tr>
					{% endif %}
						</tbody>
					{% endfor %}
				</table>
		</div>
	</div>

{% endblock %}

statistics_app/templates/statistics_app/team_stats.html
{% extends 'workshop_app/base.html' %}

{% block title %}
 Workshop  Statistics
{% endblock %}

{% block content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-md-2">
            <ul class="nav nav-pills list-group">
                {% for team in all_teams %}
                    <li class="nav-item">
                        <a href="{% url 'statistics_app:team' team.id %}" class="nav-link list-group-item">
                            Team {{forloop.counter}}
                        </a>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col-md-8">
            <br>
            <canvas id="myChart"></canvas>
        </div>
    </div>
</div>
<script>
    var ctx = document.getElementById('myChart').getContext('2d');
    var chart = new Chart(ctx, {
        // The type of chart we want to create
        type: 'bar',

        // The data for our dataset
        data: {
            labels: {{team_labels|safe}},
            datasets: [{
                data: {{ws_count|safe}},
                label: "Team Members Workshops",
                backgroundColor: 'rgb(255, 99, 132)',
                borderColor: 'rgb(255, 99, 132)',
            }]
        },
        // Configuration options go here
        options: {}
    });
</script>
{% endblock %}

statistics_app/templates/statistics_app/workshop_public_stats.html
{% extends 'workshop_app/base.html' %}

{% block title %} Statistics {% endblock %}

{% block content %}
<style>
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }

    body {
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        min-height: 100vh;
        padding: 20px;
        background: url(https://www.inclusiongeeks.com/wp-content/uploads/2023/02/business-workshop.jpg);
    }

    .container-fluid {
        max-width: 1400px;
        margin: 0 auto;
    }

    .filter-panel {
        background: rgba(255, 255, 255, 0.95);
        backdrop-filter: blur(10px);
        border-radius: 20px;
        padding: 0;
        /* box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1); */
        border: 1px solid rgba(255, 255, 255, 0.2);
        transition: transform 0.3s ease;
        margin-bottom: 20px;
    }

    .filter-panel:hover {
        transform: translateY(-5px);
    }

    .card-header {
        background: transparent;
        border: none;
        padding: 25px 25px 0 25px;
    }
    .card-header .row {
        align-items: center;
        flex-wrap: wrap;
    }
    .card-header .col-md-4 {
        display: flex;
        justify-content: flex-end;
    }

    .card-header h3 {
        color: #6b46c1;
        font-size: 1.8em;
        font-weight: 700;
        text-transform: uppercase;
        letter-spacing: 2px;
        position: relative;
        margin: 0;
    }

    .card-header h3::after {
        content: '';
        position: absolute;
        bottom: -10px;
        left: 0;
        width: 60px;
        height: 3px;
        background: linear-gradient(90deg, #ec4899, #8b5cf6);
        border-radius: 2px;
    }

    .card-body {
        padding: 25px;
    }

    .form-group {
        margin-bottom: 20px;
    }

    .card-body > div {
        margin-bottom: 20px;
    }

    .card-body label {
        display: block;
        margin-bottom: 8px;
        color: #4c1d95;
        font-weight: 600;
        font-size: 1.1em;
        text-transform: uppercase;
        letter-spacing: 0.5px;
    }

    .card-body input[type="date"],
    .card-body select {
        width: 100%;
        padding: 15px 20px;
        border: 2px solid #e5e7eb;
        border-radius: 12px;
        font-size: 1em;
        background: rgba(255, 255, 255, 0.8);
        transition: all 0.3s ease;
        outline: none;
        margin-top: 5px;
    }

    .card-body input:focus,
    .card-body select:focus {
        border-color: #8b5cf6;
        background: white;
        transform: translateY(-2px);
    }

    .btn {
        padding: 12px 12px;
        border: none;
        border-radius: 12px;
        font-size: 1em;
        font-weight: 600;
        text-decoration: none;
        display: inline-block;
        cursor: pointer;
        transition: all 0.3s ease;
        text-transform: uppercase;
        letter-spacing: 1px;
        margin: 0 5px;
    }

    .btn-success {
        background: linear-gradient(135deg, #d165c0, #af1e7a);
        color: white;
    }

    .btn-success:hover {
        background: linear-gradient(135deg, #d165c0, #af1e7a);
        transform: translateY(-3px);
    }

    .btn-info {
        background: linear-gradient(135deg, #d165c0, #af1e7a);
        color: white;
    }

    .btn-info:hover {
        background: linear-gradient(135deg, #d165c0, #af1e7a);
        transform: translateY(-3px);
    }
    
    .btn-info:hover{
        background: linear-gradient(135deg, #d165c0, #af1e7a);
        transform: translateY(-3px);
    }

    .btn-outline-info {
        background: transparent;
        color: #f63bed;
        border: 2px solid #f63bd7;
    }

    .btn-outline-info:hover {
        background: #f63bd7;
        color: white;
        transform: translateY(-3px);
    }
    
    .table-container {
        background: rgba(255, 255, 255, 0.95);
        backdrop-filter: blur(10px);
        border-radius: 20px;
        padding: 25px;
        border: 1px solid rgba(244, 151, 236, 0.4);
        transition: transform 0.3s ease;
    }

    .table-container:hover {
        transform: translateY(-5px);
    }

    .table {
        background: transparent;
        margin-bottom: 0;
    }

    .table thead th {
        background: linear-gradient(135deg, #6b46c1, #8b5cf6);
        color: white;
        border: none;
        padding: 15px;
        font-weight: 600;
        text-transform: uppercase;
        letter-spacing: 0.5px;
        font-size: 0.9em;
    }

    .table thead th:first-child {
        border-radius: 12px 0 0 12px;
    }

    .table thead th:last-child {
        border-radius: 0 12px 12px 0;
    }

    .table tbody td {
        padding: 15px;
        border: none;
        background: rgba(255, 255, 255, 0.5);
        transition: all 0.3s ease;
    }

    .table tbody tr:hover td {
        background: rgba(139, 92, 246, 0.1);
        transform: scale(1.02);
    }

    .table tbody tr:nth-child(even) td {
        background: rgba(255, 255, 255, 0.3);
    }

    .controls-row {
        margin-bottom: 20px;
    }
    #dialog {
        border-radius: 20px !important;
        background: rgba(255, 255, 255, 0.95) !important;
        backdrop-filter: blur(10px) !important;
    }

    @keyframes fadeInUp {
        from {
            opacity: 0;
            transform: translateY(30px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    .filter-panel,
    .table-container {
        animation: fadeInUp 0.6s ease-out;
    }
    .pagination .page-item.active .page-link {
        background-color: #fce4ec; 
        border-color: #f8bbd0;
        color: #ad1457;
    }
    .pagination .page-link {
        color: #6b46c1;
    }
    .pagination .page-link:hover {
        background-color: #fef3f7;
        color: #8b5cf6;
    }
    /* Responsive */
    @media (max-width: 1200px) {
        .stats-layout > .col-md-3,
        .stats-layout > .col {
            flex: 0 0 100%;
            max-width: 100%;
        }
    }

    @media (max-width: 768px) {
        .filter-panel,
        .table-container {
            margin: 10px;
            padding: 15px;
        }
        
        .card-header,
        .card-body {
            padding: 15px;
        }

        .card-header .col-md-8,
        .card-header .col-md-4 {
            flex: 0 0 100%;
            max-width: 100%;
        }
        .card-header .col-md-4 {
            justify-content: flex-start;
            margin-top: 8px;
        }

        .btn {
            display: block;
            width: 100%;
            margin: 5px 0;
        }

        .controls-row .col-md-3,
        .controls-row .col-md-6 {
            margin-bottom: 15px;
        }
    }

    input[type="checkbox"],
    input[type="radio"] {
        width: 20px;
        height: 20px;
        margin-right: 10px;
        accent-color: #8b5cf6;
    }
</style>

<div class="container-fluid">
    <div class="row stats-layout">
        <div class="col-md-3">
            <form method="GET">
                <div class="filter-panel">
                    <div class="card-header">
                        <h3><u>Filters</u></h3>
                        <div style="margin-top: 8px;">
                            <a href="{% url 'statistics_app:public' %}" class="btn btn-outline-info">
                                <i class="fa fa-times"></i>&nbsp;Clear
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div>
                            <label>From Date:</label>
                            {{form.from_date}}
                        </div>
                        <div>
                            <label>To Date:</label>
                            {{form.to_date}}
                        </div>
                        <div>
                            <label>Workshop:</label>
                            {{form.workshop_type}}
                        </div>
                        <div>
                            <label>State:</label>
                            {{form.state}}
                        </div>
                        <div>
                            <label>{{form.sort.help_text}}:</label>
                            {{form.sort}}
                        </div>
                        {% if request.user.is_authenticated %}
                        <div>
                            <label>{{form.show_workshops.help_text}}:</label>
                            {{form.show_workshops}}
                        </div>
                        {% endif %}
                        <br>
                        <div class="text-center">
                            <button type="submit" class="btn btn-success">
                                <i class="fa fa-eye"></i>&nbsp;View
                            </button>
                            <button type="submit" class="btn btn-info" name="download" value="download">
                                <i class="fa fa-download"></i>&nbsp;Download
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <div class="col">
            <div class="table-container">
                <div class="row controls-row">
                    <div class="col-md-6">
                        {% include "statistics_app/paginator.html" %}
                    </div>
                    <div class="col-md-3">
                        <button class="btn btn-info" id="state_graph">
                            <i class="fa fa-bar-chart"></i>&nbsp;State chart
                        </button>
                    </div>
                    <div class="col-md-3">
                        <button class="btn btn-info" id="type_graph">
                            <i class="fa fa-bar-chart"></i>&nbsp;Workshops chart
                        </button>
                    </div>
                </div>
                <div class="table-responsive-wrapper">
                <table class="table table-responsive-sm">
                    <thead>
                        <tr>
                            <th>Sr No.</th>
                            <th>Coordinator Name</th>
                            <th>Institute Name</th>
                            <th>Instructor Name</th>
                            <th>Workshop Name</th>
                            <th>Workshop Date</th>
                        </tr>
                    </thead>
                    {% csrf_token %}
                    {% for workshop in objects %}
                        <tbody>
                            <tr>
                                <td>{{ forloop.counter0|add:objects.start_index}}</td>
                                <td>{{ workshop.coordinator.get_full_name | capfirst }}</td>
                                <td>{{ workshop.coordinator.profile.institute | capfirst }}</td>
                                <td>{{ workshop.instructor.get_full_name | capfirst }}</td>
                                <td>{{ workshop.workshop_type.name }}</td>
                                <td>{{ workshop.date | date}}</td>
                            </tr>
                        </tbody>
                    {% endfor %}
                </table>
                </div>
                {% include "statistics_app/paginator.html" %}
            </div>
        </div>
    </div>
</div>

<!-- The Modal -->
<div id="dialog" title="Workshops Statistics">
    <canvas id="myChart"></canvas>
</div>

<script type="text/javascript">
    var state_labels = {{ws_states|safe}};
    var state_data = {{ws_count|safe}};
    var type_labels = {{ws_type|safe}};
    var type_data = {{ws_type_count|safe}};
    var chart;
    $("#state_graph").on("click", function() {
        show_graph(state_labels, state_data, "State wise workshops");
    });
    $("#type_graph").on("click", function() {
        show_graph(type_labels, type_data, "Type wise workshops");
    });

    function show_graph(labels, data, graph_name, chart_name) {
        var ctx = document.getElementById('myChart').getContext('2d');
        if(chart) chart.destroy();
        chart = new Chart(ctx, {
            // The type of chart we want to create
            type: 'bar',

            // The data for our dataset
            data: {
                labels: labels,
                datasets: [{
                    data: data,
                    label: graph_name,
                    backgroundColor: 'rgb(255, 99, 132)',
                    borderColor: 'rgb(255, 99, 132)',
                }]
            },
            // Configuration options go here
            options: {}
        });
       $("#dialog").dialog({
        width: Math.min($(window).width() * 0.9, 900),
        height: 'auto',
       resizable: false,
       modal: true,
       position: { my: "center", at: "center", of: window }
        });
    }
</script>

{% endblock %}