cms/urls.py
from django.urls import path, re_path
from cms import views

app_name = "cms"

urlpatterns = [
    # This pattern matches the home page (e.g., yoursite.com/)
    path('', views.home, name='home'),
    
    # This pattern matches any other URL and passes the path as 'permalink'
    # The 're_path' is used for regular expression matching.
    re_path(r'^(?P<permalink>.+)/$', views.home, name='permalink'),
]

workshop_app/urls.py
from django.conf.urls import url
from workshop_app import views

app_name = "workshop_app"

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.user_register, name="register"),
    url(r'^activate_user/(?P<key>.+)$', views.activate_user),
    url(r'^activate_user/$', views.activate_user),
    url(r'^login/$', views.user_login, name="login"),
    url(r'^logout/$', views.user_logout, name="logout"),
    url(r'^status$', views.workshop_status_coordinator,
        name='workshop_status_coordinator'),
    url(r'^dashboard$', views.workshop_status_instructor,
        name='workshop_status_instructor'),
    url(r'^accept_workshop/(?P<workshop_id>\d+)', views.accept_workshop,
        name='accept_workshop'),
    url(r'^change_workshop_date/(?P<workshop_id>\d+)$',
        views.change_workshop_date, name='change_workshop_date'),
    url(r'^details/(?P<workshop_id>\d+)$', views.workshop_details,
        name='workshop_details'),
    url(r'^type_details/(?P<workshop_type_id>\d+)$',
        views.workshop_type_details, name='workshop_type_details'),
    url(r'^type_tnc/(?P<workshop_type_id>\d+)$',
        views.workshop_type_tnc, name='workshop_type_tnc'),
    url(r'^propose/$', views.propose_workshop,
        name='propose_workshop'),
    url(r'^add_workshop_type$', views.add_workshop_type,
        name='add_workshop_type'),
    url(r'^delete_attachment_file/(?P<file_id>\d+)$',
        views.delete_attachment_file, name='delete_attachment_file'),
    url(r'^types/$', views.workshop_type_list,
        name='workshop_type_list'),
    url(r'^view_profile/$', views.view_own_profile,
        name='view_own_profile'),
    url(r'^view_profile/(?P<user_id>\d+)$', views.view_profile,
        name='view_profile'),
]

workshop_portal/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from workshop_portal import views
from django.conf import settings


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^workshop/', include('workshop_app.urls')),
    url(r'^reset/', include('django.contrib.auth.urls')),
    url(r'^page/', include('cms.urls')),
    url(r'^statistics/', include('statistics_app.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

workshop_app/models.py
import os
import uuid
import pandas as pd

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.utils import timezone
from django.core.validators import MinValueValidator

position_choices = (
    ("coordinator", "Coordinator"),
    ("instructor", "Instructor")
)

department_choices = (
    ("computer engineering", "Computer Science"),
    ("information technology", "Information Technology"),
    ("civil engineering", "Civil Engineering"),
    ("electrical engineering", "Electrical Engineering"),
    ("mechanical engineering", "Mechanical Engineering"),
    ("chemical engineering", "Chemical Engineering"),
    ("aerospace engineering", "Aerospace Engineering"),
    ("biosciences and bioengineering", "Biosciences and  BioEngineering"),
    ("electronics", "Electronics"),
    ("energy science and engineering", "Energy Science and Engineering"),
)

title = (
    ("Professor", "Prof."),
    ("Doctor", "Dr."),
    ("Shriman", "Shri"),
    ("Shrimati", "Smt"),
    ("Kumari", "Ku"),
    ("Mr", "Mr."),
    ("Mrs", "Mrs."),
    ("Miss", "Ms."),
)

source = (
    ("FOSSEE website", "FOSSEE website"),
    ("Google", "Google"),
    ("Social Media", "Social Media"),
    ("From other College", "From other College"),
)

states = (
    ("", "---------"),
    ("IN-AP", "Andhra Pradesh"),
    ("IN-AR", "Arunachal Pradesh"),
    ("IN-AS", "Assam"),
    ("IN-BR", "Bihar"),
    ("IN-CT", "Chhattisgarh"),
    ("IN-GA", "Goa"),
    ("IN-GJ", "Gujarat"),
    ("IN-HR", "Haryana"),
    ("IN-HP", "Himachal Pradesh"),
    ("IN-JK", "Jammu and Kashmir"),
    ("IN-JH", "Jharkhand"),
    ("IN-KA", "Karnataka"),
    ("IN-KL", "Kerala"),
    ("IN-MP", "Madhya Pradesh"),
    ("IN-MH", "Maharashtra"),
    ("IN-MN", "Manipur"),
    ("IN-ML", "Meghalaya"),
    ("IN-MZ", "Mizoram"),
    ("IN-NL", "Nagaland"),
    ("IN-OR", "Odisha"),
    ("IN-PB", "Punjab"),
    ("IN-RJ", "Rajasthan"),
    ("IN-SK", "Sikkim"),
    ("IN-TN", "Tamil Nadu"),
    ("IN-TG", "Telangana"),
    ("IN-TR", "Tripura"),
    ("IN-UT", "Uttarakhand"),
    ("IN-UP", "Uttar Pradesh"),
    ("IN-WB", "West Bengal"),
    ("IN-AN", "Andaman and Nicobar Islands"),
    ("IN-CH", "Chandigarh"),
    ("IN-DN", "Dadra and Nagar Haveli"),
    ("IN-DD", "Daman and Diu"),
    ("IN-DL", "Delhi"),
    ("IN-LD", "Lakshadweep"),
    ("IN-PY", "Puducherry")
)


def has_profile(user):
    """ check if user has profile """
    return hasattr(user, 'profile')


def attachments(instance, filename):
    return os.sep.join((instance.workshop_type.name.replace(" ", '_'), filename))


class Profile(models.Model):
    """Profile for users(instructors and coordinators)"""

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=32, blank=True, choices=title)
    institute = models.CharField(max_length=150)
    department = models.CharField(max_length=150, choices=department_choices)
    phone_number = models.CharField(
        max_length=10,
        validators=[RegexValidator(
            regex=r'^.{10}$', message=(
                "Phone number must be entered \
                in the format: '9999999999'.\
                Up to 10 digits allowed.")
        )], null=False)
    position = models.CharField(
            max_length=32, choices=position_choices,
            default='coordinator',
            help_text='Select Coordinator if you want to organise a workshop\
         in your college/school. <br> Select Instructor if you want to conduct\
                 a workshop.')
    how_did_you_hear_about_us = models.CharField(
        max_length=255, blank=True, choices=source
    )
    location = models.CharField(
        max_length=255, blank=True, help_text="Place/City"
    )
    state = models.CharField(max_length=255, choices=states, default="IN-MH")
    is_email_verified = models.BooleanField(default=False)
    activation_key = models.CharField(max_length=255, blank=True, null=True)
    key_expiry_time = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return f"Profile for {self.user.get_full_name()}"


class WorkshopType(models.Model):
    """"Admin creates types of workshops which can be used by the instructor
        to create workshops.
    """

    name = models.CharField(max_length=120)
    description = models.TextField()
    duration = models.PositiveIntegerField(
        help_text='Please enter duration in days',
        validators=[MinValueValidator(1)]
    )
    terms_and_conditions = models.TextField()

    def __str__(self):
        return f"{self.name} for {self.duration} day(s)"


class AttachmentFile(models.Model):
    attachments = models.FileField(
        upload_to=attachments, blank=False,
        help_text='Please upload workshop documents one by one, \
                    ie.workshop schedule, instructions etc. \
                    Please Note: Name of Schedule file should be similar to \
                    WorkshopType Name')
    workshop_type = models.ForeignKey(WorkshopType, on_delete=models.CASCADE)


class WorkshopManager(models.Manager):

    def get_workshops_by_state(self, workshops):
        w = workshops.values_list("coordinator__profile__state", flat=True)
        states_map = dict(states)
        df = pd.DataFrame(list(w))
        data_states, data_counts = [], []
        if not df.empty:
            grouped_data = df.value_counts().to_dict()
            for state, count in grouped_data.items():
                state_name = state[0]
                data_states.append(states_map[state_name])
                data_counts.append(count)
        return data_states, data_counts

    def get_workshops_by_type(self, workshops):
        w = workshops.values_list("workshop_type__name", flat=True)
        df = pd.DataFrame(list(w))
        data_wstypes, data_counts = [], []
        if not df.empty:
            grouped_data = df.value_counts().to_dict()
            for ws, count in grouped_data.items():
                ws_name = ws[0]
                data_wstypes.append(ws_name)
                data_counts.append(count)
        return data_wstypes, data_counts


class Workshop(models.Model):
    """
        Contains details of workshops
    """
    uid = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    coordinator = models.ForeignKey(User, on_delete=models.CASCADE)
    instructor = models.ForeignKey(
        User, null=True, related_name="%(app_label)s_%(class)s_related",
        on_delete=models.CASCADE
    )
    workshop_type = models.ForeignKey(
        WorkshopType, on_delete=models.CASCADE,
        help_text='Select the type of workshop.'
    )
    date = models.DateField()
    STATUS_CHOICES = [(0, 'Pending'),
                      (1, 'Accepted'),
                      (2, 'Deleted')]

    status = models.IntegerField(choices=STATUS_CHOICES, default=0)
    tnc_accepted = models.BooleanField(
        help_text="I accept the terms and conditions"
    )

    objects = WorkshopManager()

    def __str__(self):
        return f"{self.workshop_type} on {self.date} by {self.coordinator}"

    def get_status(self):
        choice = dict(self.STATUS_CHOICES)
        return choice.get(self.status)




class Testimonial(models.Model):
    """
    Contains Testimonals of Workshops
    """

    name = models.CharField(max_length=150)
    institute = models.CharField(max_length=255)
    department = models.CharField(max_length=150)
    message = models.TextField()

    def __str__(self):
        return f"Testimonial by {self.name}"


class Comment(models.Model):
    """
    Contains comments posted by users on workshop instances
    """

    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    public = models.BooleanField(default=True)
    created_date = models.DateTimeField(default=timezone.now)
    workshop = models.ForeignKey(Workshop, on_delete=models.CASCADE)

    def __str__(self):
        return f"Comment by {self.author.get_full_name()}"


class Banner(models.Model):
    """
    Add HTML for banner display on homepage
    """
    title = models.CharField(max_length=500)
    html = models.TextField()
    active = models.BooleanField()

    def __str__(self):
        return self.title

workshop_app/templates/workshop_app/activation.html
{% extends 'workshop_app/base.html' %}

{% block title %}
    Awaiting activation
{% endblock %}

{% block header %}
    <nav class="navbar navbar-default navbar-dark bg-dark">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand text-white" href="/">
                    FOSSEE Workshops
                </a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.profile.is_email_verified %}
                    <li><a href="{% url 'workshop_app:view_profile' %}"><span class="glyphicon glyphicon-user"></span>
                        Profile</a></li>

                    <li><a href="{% url 'workshop_app:logout' %}"><span class="glyphicon glyphicon-log-out"></span> Logout</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
{% endblock %}

{% block extra %}

{% endblock %}

{% block content %}
    {% if status == '2' %}
        <div class="container">
            <div class="jumbotron">
                <p> Your email is already verified, Click
                    <a href="{% url 'workshop_app:index' %}">here</a>
                </p>
            </div>
        </div>
    {% elif status == '1' %}
        <script type="text/javascript">
            window.setTimeout(function () {
                location.href = "{% url 'workshop_app:register' %}"
            }, 3000);
        </script>
        <div class="container">
            <div class="jumbotron">
                <p> Your activation has expired please register again</p>
            </div>
        </div>
    {% elif status == '0' %}
        <div class="container">
            <div class="jumbotron">
                <p> Your account has been activated. Click
                    <a href="{% url 'workshop_app:index' %}">here</a>
                </p>
            </div>
        </div>
    {% else %}
        <script type="text/javascript">
            window.setTimeout(function () {
                location.href = "{% url 'workshop_app:logout' %}"
            }, 5000);
        </script>

        <div class="container">
            <div class="jumbotron">
                <h1>Activation Awaiting</h1>
                <p>The Activation Link has been sent to your email. The link expires in <strong>24hours</strong> from
                    the date of registration. You will be logged out automatically
                </p>
            </div>
        </div>
    {% endif %}
{% endblock %}

workshop_app/templates/workshop_app/edit_profile.html
{% extends "workshop_app/base.html" %}

{% block title %}
	Edit Profile
{% endblock %}

{% block content %}
  <div class="container">
    <form action="{{URL_ROOT}}/edit_profile/" method="post" >
    {% csrf_token %}
      <center>
        <table class="table table-bordered">
          {{ form.as_table }}
        </table>
      </center>
      <br>
        <button class="btn btn-primary pull-right" type="submit">Save Profile</button>
    </form>
  </div>
{% endblock %}

workshop_app/templates/workshop_app/view_profile.html
{% extends 'workshop_app/base.html' %}

{% block title %} Profile {% endblock %}

{% csrf_token %}
{% block content %}
    <style>
        .container {
            background: lightpink;
            padding: 0 !important;
        }
        .btn {
            padding: 15px 30px;
            border: none;
            border-radius: 12px;
            font-size: 1.1em;
            font-weight: 600;
            text-decoration: none;
            display: inline-block;
            cursor: pointer;
            transition: all 0.3s ease;
            text-transform: uppercase;
            letter-spacing: 1px;
            margin: 0 10px;
        }

        .btn-primary, .btn-success {
            background: linear-gradient(135deg, #d152b7, #480527);
            color: white;
        }

        .btn-primary:hover, .btn-success:hover {
            transform: translateY(-3px);
            text-decoration: none;
            color: white;
        }

        .btn-link {
            background: transparent;
            color: #8b5cf6;
            border: 2px solid #8b5cf6;
        }

        .btn-link:hover {
            background: #8b5cf6;
            color: white;
            transform: translateY(-3px);
            text-decoration: none;
        }

    </style>
    <div class="container">
        <h2 class="text-center mt-4 mb-4">Profile</h2>
        {% if Workshops %}
        
            <table class="table table-bordered">
                <tr>
                    <th><label for="id_first_name"><h5>First name:</h5></label></th>
                    <th><label for="id_first_name"><h5>{{ coordinator_profile.user.first_name }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_last_name"><h5>Last name:</h5></label></th>
                    <th><label for="id_last_name"><h5>{{ coordinator_profile.user.last_name }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_email"><h5>Email:</h5></label></th>
                    <th><label for="id_email"><h5>{{ coordinator_profile.user.email }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_institute"><h5>Institute:</h5></label></th>
                    <th><label for="id_institute"><h5>{{ coordinator_profile.user.profile.institute }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_phone_number"><h5>Phone Number:</h5></label></th>
                    <th><label for="id_phone_number"><h5>{{ coordinator_profile.user.profile.phone_number }}</h5></label>
                    </th>
                </tr>
                <tr>
                    <th><label for="id_department"><h5>Department:</h5></label></th>
                    <th><label for="id_department"><h5>{{ coordinator_profile.user.profile.department }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_location"><h5>Location:</h5></label></th>
                    <th><label for="id_location"><h5>{{ coordinator_profile.user.profile.location }}</h5></label></th>
                </tr>
                <tr>
                    <th><label for="id_position"><h5>Position:</h5></label></th>
                    <th><label for="id_position"><h5>{{ coordinator_profile.user.profile.position }}</h5></label></th>
                </tr>
            </table>
            <br>

            <div class="container">
            <h2>Workshop Details</h2>
            <table class="table table-bordered">
            <tr>
                <th><label for="id_instructor_name">Instructor name</label></th>
                <th><label for="id_workshop_date">Workshop date</label></th>
                <th><label for="id_workshop_type">Workshop type</label></th>
            </tr>
            {% for workshop in Workshops %}
                {% if workshop.instructor %}
                    <tr>
                        <td><label for="id_instructor_name">{{ workshop.instructor }}
                        </label></td>
                        <td><label for="id_workshop_date">{{ workshop.date }}</label>
                        </td>
                        <td><label for="id_workshop_type">{{ workshop.workshop_type }}</label>
                        </td>
                    </tr>
                {% else %}
                    <tr>
                        <td><span class="badge badge-warning">Pending</span></td>
                        <td><label for="id_workshop_date">{{ workshop.date }}</label>
                        </td>
                        <td><label for="id_workshop_type">{{ workshop.workshop_type }}</label>
                        </td>
                    </tr>
                {% endif %}
            {% endfor %}
            </table>
            </div>
            <br><br>
        {% else %}
            <form action="" method="post">
              {% csrf_token %}
                <div class="row justify-content-center form-group">
                    <div class="col-md-6">
                    <form action="" method="post">
                        <fieldset>
                            {% csrf_token %}
                            {% if form.errors %}
                                {% for field in form %}
                                    {% for error in field.errors %}
                                        <div class="alert alert-dismissible alert-danger">
                                            <button type="button" class="close" data-dismiss="alert">
                                                <i class="fa fa-close"></i>
                                            </button>
                                            <strong>{{field.label}} : {{ error|escape }}</strong>
                                        </div>
                                    {% endfor %}
                                {% endfor %}
                                {% for error in form.non_field_errors %}
                                    <div class="alert alert-dismissible alert-danger">
                                        <button type="button" class="close" data-dismiss="alert">
                                            <i class="fa fa-close"></i>
                                        </button>
                                        <strong>{{field.label}} : {{ error|escape }}</strong>
                                    </div>
                                {% endfor %}
                            {% endif %}
                            <table class="table table-responsive-sm">
                                <tr><td>{{form.title}}</td></tr>
                                <tr><td>{{form.first_name}}</td></tr>
                                <tr><td>{{form.last_name}}</td></tr>
                                <tr><td>{{form.phone_number}}</td></tr>
                                <tr><td>{{form.institute}}</td></tr>
                                <tr><td>{{form.department}}</td></tr>
                                <tr><td>{{form.position}}</td></tr>
                                <tr><td>{{form.location}}</td></tr>
                                <tr><td>{{form.state}}</td></tr>
                            </table>
                            <br>
                        </fieldset>
                        <button class="btn btn-success btn-lg" type="submit">
                            <i class="fa fa-pencil-square-o"></i>&nbsp;Update</button>
                        <a href="{% url 'workshop_app:index' %}" class="btn btn-primary btn-lg">Cancel
                        </a>
                    </form>
                    </div>
                </div>
            </form>
        {% endif %}
    </div>
{% endblock %}

workshop_app/templates/workshop_app/workshop_details.html
{% extends 'workshop_app/base.html' %}

{% block title %}
    View Workshop details
{% endblock %}

{% block content %}
    <div class="container">
        <table class="table table-bordered">
            <tr>
                <th><label for="id_first_name">Workshop Type :</label></th>
                <td><label for="id_first_name"><a
                        href="{% url 'workshop_app:workshop_type_details' workshop.workshop_type_id %}">{{ workshop.workshop_type }}</a></label>
                </td>
            </tr>
            <tr>
                <th><label for="id_last_name">Date :</label></th>
                <td><label for="id_last_name">{{ workshop.date }}</label></td>
            </tr>
            <tr>
                <th><label for="id_email">Coordinator :</label></th>
                <td><label for="id_email">{{ workshop.coordinator.get_full_name|title }}</label>
                </td>
            </tr>
            {% if workshop.status %}
                <tr>
                    <th><label for="id_institute">Status :</label></th>
                    <td><span class="badge badge-success">{{ workshop.get_status }}</span></td>
                </tr>
                <tr>
                    <th><label for="id_phone_number">Instructor :</label></th>
                    <td><label for="id_email">{{ workshop.instructor.get_full_name|title }}</label>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <th><label for="id_institute">Status :</label></th>
                    <td><span class="badge badge-warning">{{ workshop.get_status }}</span></td>
                </tr>
            {% endif %}
        </table>
        <br>
        <div class="container">
            <div class="card mt-2 mb-5">
                <form method="post">
                    <div class="card-header">
                        <div class="row">
                            <div class="mx-3 font-weight-bold">Post a comment</div>
                            {% if request.user.profile.position == 'instructor' %}
                                <div class="ml-5">{{ form.public }} Public</div>
                                <div class="ml-1 text-muted">(Non-public comments are visible only to instructors)</div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="card-body">
                        {{ form.comment }}
                    </div>
                    <button type="submit" class="float-right btn btn-primary btn-md m-2">Post</button>
                </form>
            </div>
            <br><br>
            <h2 class="text-center">Comments</h2>
            <br>
            {% for comment in workshop_comments %}
                <div class="card my-2">
                    <div class="card-header">
                        <div class="row">
                            <div class="ml-3 font-weight-bold"><a
                                    href="{% url 'workshop_app:view_profile' comment.author_id %}">{{ comment.author }}</a></div>
                            {% if not comment.public %}
                                <div class="ml-1"><span class="badge badge-dark">Hidden</span></div>
                            {% endif %}
                            <div class="ml-3 text-muted">{{ comment.created_date }}</div>
                        </div>
                    </div>
                    <div class="card-body">
                        <p>{{ comment.comment }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

workshop_app/templates/workshop_app/workshop_type_list.html
{% extends 'workshop_app/base.html' %}
{% load custom_filters %}
{% load static %}
{% block title %}
View List of available Workshops
{% endblock %}
{% block content %}

<style>
body {
font-family: 'Inter', sans-serif;
background: linear-gradient(to right, #ece9e6, #ffffff);
color: #333;
}

.container {
padding: 40px;
}
.current{
    color: white;
}
@keyframes fadeInUp {
from {
opacity: 0;
transform: translateY(20px);
}
to {
opacity: 1;
transform: translateY(0);
}
}

@keyframes pulse {
0% {
transform: scale(1);
}
50% {
transform: scale(1.03);
}
100% {
transform: scale(1);
}
}

.workshop-heading {
display: flex;
justify-content: center;
height: 150px;
margin-bottom: 30px;
animation: fadeInUp 0.8s ease-out;
background: linear-gradient(to right, #7b7bca, #5b5b8d);
border-radius: 20px;
}
h2{
color: white;
font-weight: 900;
font-size: 2.5rem;
align-self: center;
}

.table {
background-color: #ffffff;
border-radius: 12px;
box-shadow: 0 10px 25px rgba(0, 0, 0, 0.1);
overflow: hidden;
animation: fadeInUp 1s ease-out;
}

.table thead {
background-color: #e9f0f9;
}

.table th {
font-weight: 700;
color: #4a5568;
padding: 1.2rem 1.5rem;
vertical-align: middle;
}

.table td {
color: #718096;
padding: 1.2rem 1.5rem;
vertical-align: middle;
}

.table tbody tr:hover {
background-color: #f0f4f9;
transform: translateY(-2px);
box-shadow: 0 4px 10px rgba(0, 0, 0, 0.08);
transition: all 0.3s ease;
}

.btn.btn-outline-info {
border-radius: 50px;
border: 2px solid #d593ba;
color: #d593ba;
font-weight: 600;
padding: 8px 24px;
transition: all 0.3s ease;
}

.btn.btn-outline-info:hover {
background-color: #d593ba;
color: #fff;
box-shadow: 0 4px 15px rgba(223, 141, 210, 0.4);
}

.btn.btn-primary {
background: linear-gradient(45deg, #be629a, #ca2382);
border-color: #b967a0;
border-radius: 50px;
font-weight: 600;
padding: 10px 28px;
transition: all 0.3s ease;
animation: pulse 2s infinite;
}

.btn.btn-primary:hover {
box-shadow: 0 4px 15px rgba(0, 123, 255, 0.4);
transform: scale(1.05);
}
.table-responsive {
    overflow-x: auto;
    -webkit-overflow-scrolling: touch; 
}

.modal-content {
border-radius: 12px;
box-shadow: 0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05);
}

.pagination .page-item a {
border-radius: 6px;
margin: 0 4px;
color: #4a5568;
}

.pagination .page-item a:hover {
background-color: #e2e8f0;
}
.workshop-heading{
    background-image: url(https://tse4.mm.bing.net/th/id/OIP.2pA3NhoRAIMC0c3xuVuqRgHaDI?w=1300&h=550&rs=1&pid=ImgDetMain&o=7&rm=3);
    background-repeat: no-repeat;
    background-attachment: fixed;
    background-position: center;
    background-size: cover;
}
.container{
    background-color: rgb(114, 114, 215);
}

</style>

<div class="container">
<div class="workshop-heading">
 <h2>WORKSHOP TYPES</h2>
</div>
<br>
<div class="bgblue">
{% if request.user|has_group:"__instructor__" %}
<a href="{% url 'workshop_app:add_workshop_type' %}">
<button class="btn btn-md btn-primary float-right mb-3 mx-4">Add Workshop Type</button>
</a>
<br>
{% endif %}
<div class="container table-responsive">
<table class="table table-hover">
<thead>
<tr>
<th>Sr No</th>
<th>Workshop Name</th>
<th>Workshop Duration (Days)</th>
<th>Action</th>
</tr>
</thead>
{% for w in workshop_type %}
<tbody>
<tr >
<td scope="row" id="{{ forloop.counter }}">{{ forloop.counter }}</td>
<td>{{ w.name }}</td>
<td>{{ w.duration }}</td>
<td><a href="{% url 'workshop_app:workshop_type_details' w.id %}" class="btn btn-outline-info" class="accordion-toggle" >View Workshop Details</a></td>
</tr>
</tbody>
{% endfor %}
</table>
</div>
<!-- The Modal -->
<div id="mailModal" class="modal">
<!-- Modal content -->
<div class="modal-content">
<span class="close">×</span>
<p>Separate Multiple Email Id's using <strong> comma (,)</strong></p>
<form action="{{URL_ROOT}}/share_details/" method="POST">
{% csrf_token %}
<label > Email: </label>
<input name="email" type='email' multiple>
<input type='submit'>
</form>
</div>
</div>
<!-- Page Navigation -->
<div class="container">
<div class="Page-Nav" align="center">
<nav aria-label="Page navigation">
<ul class="pagination pagination-sm">
<li class="page-item">
{% if workshoptype.has_previous %}
<a class="page-link" tabindex="-1"
href="?page={{ workshop_type.previous_page_number }}">Previous</a>
{% endif %}
</li>
<li class="page-item">
<span class="current">
Page {{ workshop_type.number }} of {{ workshop_type.paginator.num_pages }}
</span>
</li>
<li class="page-item">
{% if workshop_type.has_next %}
<a class="page-link" href="?page={{ workshop_type.next_page_number }}">Next
</a>
{% endif %}
</li>
</ul>
</nav>
</div>
</div>
</div>
</div>
{% endblock %}